#!/usr/bin/env bash
# These are the UFW commands to block all incoming traffic except for ports 22, 80, and 443

# Install UFW
sudo apt-get install ufw -y

# Deny all incoming traffic by default
sudo ufw default deny incoming

# Allow all outgoing traffic
sudo ufw default allow outgoing

# Allow SSH traffic on port 22
sudo ufw allow 22/tcp

# Allow HTTP traffic on port 80
sudo ufw allow 80/tcp

# Allow HTTPS traffic on port 443
sudo ufw allow 443/tcp

# Enable the firewall (with --force to skip the 'y/n' prompt in a script)
sudo ufw --force enable

# Display the status of the firewall
sudo ufw status

